# -------------------------------------------------------------------------
# ---------------------------- Libraries/Packages -------------------------
# -------------------------------------------------------------------------

box::use(
  shiny[a, br, div, h4, p, span],
  shiny.semantic[action_button, modal]
)

# -------------------------------------------------------------------------
# ---------------------------------- Modules ------------------------------
# -------------------------------------------------------------------------

# box::use(
#   
# )

# --------------------------------------------
# ----- Function to Build the Info Modal -----
# --------------------------------------------

#' @export
build_modal <- function(modal_id, params) {
  modal(
    id = modal_id,
    header = list(h4(class = "modal-title",
                     "Answer")),
    footer = action_button(input_id = "dismiss_modal",
                           label = "Dismiss",
                           class = "ui positive button"),
    settings = list(c("transition", "fly down")),
    content = list(
        div(class = "answer-container",
            "This data was generated by an ARIMA(", params$p, ",", params$d, ",", params$q, ")", "process."),
        br(),
        p(class = "modal-paragraph", 
            "However, it is likely that you may have decided upon a different answer. 
          It is important to remember that, when modeling data, a more parsimonious and less complex
          model can often perform just as well, if not better, than a more complex model. It's often not necessary
          to include as many parameters to model a complex data generating process. Indeed, it may be 
          preferable, since the data generating process could be changing over time and modeling its
          values during a certain time period too closely could result in bad forecasts later on. "),
        br(),
        p(class = "modal-paragraph", 
          "Ultimately, ARIMA modeling is a subjective art that requires practice,
          and it is up to the modeler to judge potential models using best practices. Remember, check you AIC 
          and BIC values to monitor complexity, and check your diagnostic plots to ensure model assumptions are met."),
        br(),
        div(class = "answer-container",
            "To try a different series, reload the web page.")
    )
  )
}
